include "akka"

interop-be-attributes-loader {
  ec-keys-identifiers = ""
  rsa-keys-identifiers = ""
  ec-keys-identifiers = ${?EC_KEYS_IDENTIFIERS}
  rsa-keys-identifiers = ${?RSA_KEYS_IDENTIFIERS}

  signer-max-connections = 5
  signer-max-connections = ${?KMS_MAX_CONCURRENCY}

  services {
     attribute-registry-management = ${ATTRIBUTE_REGISTRY_MANAGEMENT_URL}
  }
}

interop-commons {
  vault {
    address = ${VAULT_ADDR}
    token = ${VAULT_TOKEN}
    signature-route = ${VAULT_SIGNATURE_ROUTE}
  }

  jwt {
    internal-token {
      issuer = ${JWT_ISSUER}
      subject = ${JWT_SUBJECT}
      audience = ${JWT_AUDIENCE}
      duration-seconds = ${JWT_DURATION_SECONDS}
    }
  }
}

futures-dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    core-pool-size-min = 4
    core-pool-size-factor = 1.0
    core-pool-size-max = 16
    max-pool-size-min = 4
    max-pool-size-factor = 1.0
    max-pool-size-max = 16
  }
  throughput = 1
  throughput = ${?BLOCKING_DISPATCHER_THROUGHPUT}
}